variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go'
    appType: 'webAppLinux'
    appName: 'Demo-Service'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'